spring.application.name=ecom-app
server.port=8081
spring.datasource.url=jdbc:h2:file:./data/ecom;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=false
spring.jpa.open-in-view=false
